### ISSUE TITLE
ChilizChainでのコントラクトデプロイとverify

### ISSUE THREAD

**Issue by ikmzkro** [ikmzkro/vsl-token#41]
https://docs.chiliz.com/quick-start/deploy-and-verify-a-contract

**Comment by ikmzkro** [comment]
なんか1デプロイは成功した。
２回目のデプロイ以降はこける。
```
$ npx hardhat run scripts/deployMyNFT.ts --network chiliz
ProviderError: insufficient funds for gas * price + value: balance 2873372088000000000, tx cost 4244333554687500000, overshot 1370961466687500000
    at HttpProvider.request (/home/ikmz/Chiliz-Sports-Hackathon/contract/node_modules/hardhat/src/internal/core/providers/http.ts:96:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HardhatEthersSigner.sendTransaction (/home/ikmz/Chiliz-Sports-Hackathon/contract/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async ContractFactory.deploy (/home/ikmz/Chiliz-Sports-Hackathon/contract/node_modules/ethers/src.ts/contract/factory.ts:111:24)
    at async main (/home/ikmz/Chiliz-Sports-Hackathon/contract/scripts/deployMyNFT.ts:9:17)
```

単にネットワークエラー、指定先のネットワークが違う等かと思ったが
アドレスの残高を見るとCHZが焼失しまくってたので（16→2）単純なガス不足の可能性もある。

**Comment by ikmzkro** [comment]
まあseploidaでできるならspycyでもできるだろうという目測でいったんsepoliaで進めるか

**Comment by ikmzkro** [comment]
## ERC721

- [ ] chilizchainでコントラクトデプロイ
- [ ] chilizchainでコントラクト検証
- [ ] chilizchainで発行を動作確認
- [ ] Dapps/chilizchainでの表示確認

## ERC20

- [ ] FanToken→VSLトークンにしましょう（ヴィッセル神戸）
- [ ] chilizchainでコントラクトデプロイ
- [ ] chilizchainでコントラクト検証
- [ ] chilizchainで発行と転送を動作確認
- [ ] Dapps/chilizchainでの表示確認

**Comment by ikmzkro** [comment]
hardhatではverifyできないっぽいのでもうこの辺にしておく
コントラクトだけデプロイする。

**Comment by ikmzkro** [comment]
全体構想に対して動いた内容のみ提出する
今回はあまりにも時間が少なくスキルもまばらでしょうがなかった
まあでも課題解決に向けた自己学習的アプローチができたのでよし

**Comment by ikmzkro** [comment]
課題とすて秘密計算系を進めたい
Dapps系作れないのつらいｎ
